---
# -*- coding: utf-8 -*-

before_script:
  - env
  - hostname
  - ip r
  - du --max-depth=1
  - uname -a
  - ansible --version
  - ansible-lint --version
  - awx-cli --version

stages:
  - ansible-lint
  - ansible-syntax-check
  - ansible-awx

ansible-lint:
  stage: ansible-lint
  script:
    - make PLAYBOOK=test.yml lint
    - make PLAYBOOK=dmi-validate.yml lint
    - make PLAYBOOK=wol-wait-install.yml lint
    - make PLAYBOOK=wol-wait-lspci.yml lint
    - make PLAYBOOK=wol-wait-system-info.yml lint
  tags:
    - ansible

ansible-syntax-check:
  stage: ansible-syntax-check
  script:
    - make syntax
  tags:
    - ansible

ansible-awx-wst-hpt-bio:
  stage: ansible-awx
  script:
    - make awx_version
    - make awx_user
    - make AWX_GITLAB_JOB_LAUNCH=wst_hpt_bio_v0.2.3 awx_job_launch
  when: manual
  tags:
    - awx

ansible-awx-wst-hpt-dmi:
  stage: ansible-awx
  script:
    - make awx_version
    - make awx_user
    - make AWX_GITLAB_JOB_LAUNCH=wst_hpt_dmi_v0.1.0 awx_job_launch
  when: manual
  tags:
    - awx

ansible-awx-wst-hpt-pci:
  stage: ansible-awx
  script:
    - make awx_version
    - make awx_user
    - make AWX_GITLAB_JOB_LAUNCH=wst_hpt_pci_v0.2.3 awx_job_launch
  when: manual
  tags:
    - awx
