---

- name: (hp linux tools) build
  shell: make
  args:
    executable: /bin/bash
    chdir: "{{ hplt_dir }}/{{ hplt_distro_dir }}/hpuefi-mod-3.03"
  become: yes
  when: hplt_build_make | bool
  #register: hplt_build_make_status

- name: (hp linux tools) install
  shell: make install
  args:
    executable: /bin/bash
    chdir: "{{ hplt_dir }}/{{ hplt_distro_dir }}/hpuefi-mod-3.03"
  become: yes
  when: hplt_build_install | bool
