---

- name: (hp linux tools) get lspci information
  command: lspci -vv -s {{ hplt_lspci_eth_device }}
  register: hplt_lspci_eth_device_register
  become: yes
  when:
    - hplt_lspci_eth_device_info is defined
    - hplt_lspci_eth_device_info | bool
    - hplt_lspci_eth_device is defined

- name: (hp linux tools) show lspci information filtered by '{{ hplt_lspci_eth_status }}'
  debug:
    msg: "{{ hplt_lspci_eth_device_register.stdout | regex_search(hplt_lspci_eth_status) }}"
  when:
    - hplt_lspci_eth_device_info is defined
    - hplt_lspci_eth_device_info | bool
    - hplt_lspci_eth_device_register is defined
    - hplt_lspci_eth_status is defined

- name: (hp linux tools) fail when '{{ hplt_lspci_eth_status }}' not found
  fail:
  when:
    - hplt_lspci_eth_status_fail_not_found is defined
    - hplt_lspci_eth_status_fail_not_found | bool
    - hplt_lspci_eth_device_status is defined
    - hplt_lspci_eth_device_status | bool
    - hplt_lspci_eth_status is defined
    - hplt_lspci_eth_device_register is defined
    - not hplt_lspci_eth_device_register.stdout | regex_search(hplt_lspci_eth_status)

- name: (hp linux tools) fail when '{{ hplt_lspci_eth_status }}' found
  fail:
  when:
    - hplt_lspci_eth_status_fail_found is defined
    - hplt_lspci_eth_status_fail_found | bool
    - hplt_lspci_eth_device_status is defined
    - hplt_lspci_eth_device_status | bool
    - hplt_lspci_eth_status is defined
    - hplt_lspci_eth_device_register.stdout | regex_search(hplt_lspci_eth_status)
