---

- name: (hp linux tools) BIOS download HPSETUP if missing or checksum differs
  get_url:
    url: "{{ hplt_repsetup_hpsetup_file_url }}"
    dest: "{{ hplt_repsetup_hpsetup_file_path }}"
    checksum: "{{ hplt_algorithm | lower }}:{{ hplt_repsetup_hpsetup_file_checksum }}"
    use_proxy: "{{ hplt_proxy_use }}"
    timeout: "{{ hplt_download_timeout | default(300) }}"
  environment: "{{ hplt_proxy_environment }}"
  become: yes
  when:
    - hplt_repsetup_hpsetup_down | bool
    - not hplt_repsetup_hpsetup_get | bool

- name: (hp linux tools) ensure hp-repsetup is executable
  file:
    path: "{{ hplt_repsetup_command_bin }}"
    owner: "{{ hplt_repsetup_owner }}"
    mode: "{{ hplt_repsetup_mode }}"
  become: yes

- name: (hp linux tools) BIOS get HPSETUP
  shell: "{{ hplt_repsetup_command_get }} > {{ hplt_repsetup_hpsetup_file_path }}"
  args:
    executable: /bin/bash
  become: yes
  when:
    - hplt_repsetup_hpsetup_get | bool
    - not hplt_repsetup_hpsetup_down | bool

- name: (hp linux tools) BIOS show HPSETUP
  command: strings {{ hplt_repsetup_hpsetup_file_path }}
  become: yes
  when: hplt_repsetup_hpsetup_show | bool

- name: (hp linux tools) fails when hplt_repsetup_password_current has invalid
  fail:
    msg: hplt_repsetup_password_current has invalid {{ hplt_repsetup_password_invalid }}
  no_log: "{{ hplt_repsetup_hpsetup_set_no_log | default(true) }}"
  when:
    - hplt_repsetup_password_invalid in hplt_repsetup_password_current | list | first

- name: (hp linux tools) BIOS test/set Admin Password
  command: "{{ hplt_repsetup_command_tst }}"
  ignore_errors: True
  no_log: "{{ hplt_repsetup_hpsetup_set_no_log | default(true) }}"
  register: hplt_repsetup_hpsetup_tst_register
  become: yes
  when:
    - hplt_repsetup_hpsetup_set is defined
    - hplt_repsetup_hpsetup_set | bool

- name: (hp linux tools) enable hplt_repsetup_hpsetup_pwd_admin when Admin Password test is successful
  set_fact:
    hplt_repsetup_hpsetup_pwd_admin: true
  when:
    - hplt_repsetup_hpsetup_tst_register is defined
    - hplt_repsetup_hpsetup_tst_register.failed is defined
    - not hplt_repsetup_hpsetup_tst_register.failed | bool
    - hplt_repsetup_hpsetup_tst_register.rc == 0
    - hplt_repsetup_hpsetup_pwd_success in hplt_repsetup_hpsetup_tst_register.stdout

- name: (hp linux tools) BIOS set HPSETUP using Admin Password
  command: "{{ hplt_repsetup_command_set }} -p {{ hplt_repsetup_password_current }} {{ hplt_repsetup_hpsetup_file_path }}"
  ignore_errors: True
  no_log: "{{ hplt_repsetup_hpsetup_set_no_log | default(true) }}"
  register: hplt_repsetup_hpsetup_set_register
  become: yes
  when:
    - hplt_repsetup_hpsetup_set is defined
    - hplt_repsetup_hpsetup_set | bool
    - hplt_repsetup_hpsetup_pwd_admin is defined
    - hplt_repsetup_hpsetup_pwd_admin | bool

- name: (hp linux tools) fail when found '{{ hplt_repsetup_hpsetup_access_denied }}' in BIOS set HPSETUP using Admin Password
  fail:
  when:
    - hplt_repsetup_hpsetup_set is defined
    - hplt_repsetup_hpsetup_set | bool
    - hplt_repsetup_hpsetup_pwd_admin is defined
    - hplt_repsetup_hpsetup_pwd_admin | bool
    - hplt_repsetup_hpsetup_fail is defined
    - hplt_repsetup_hpsetup_fail | bool
    - hplt_repsetup_hpsetup_access_denied is defined
    - hplt_repsetup_hpsetup_set_register is defined
    - hplt_repsetup_hpsetup_access_denied in hplt_repsetup_hpsetup_set_register.stdout

- name: (hp linux tools) BIOS set HPSETUP without Admin Password
  command: "{{ hplt_repsetup_command_set }} {{ hplt_repsetup_hpsetup_file_path }}"
  ignore_errors: True
  no_log: "{{ hplt_repsetup_hpsetup_set_no_log | default(true) }}"
  register: hplt_repsetup_hpsetup_set_register
  become: yes
  when:
    - hplt_repsetup_hpsetup_set is defined
    - hplt_repsetup_hpsetup_set | bool
    - hplt_repsetup_hpsetup_pwd_admin is defined
    - not hplt_repsetup_hpsetup_pwd_admin | bool

- name: (hp linux tools) fail when found '{{ hplt_repsetup_hpsetup_access_denied }}' in BIOS set HPSETUP without Admin Password
  fail:
  when:
    - hplt_repsetup_hpsetup_set is defined
    - hplt_repsetup_hpsetup_set | bool
    - hplt_repsetup_hpsetup_pwd_admin is defined
    - not hplt_repsetup_hpsetup_pwd_admin | bool
    - hplt_repsetup_hpsetup_fail is defined
    - hplt_repsetup_hpsetup_fail | bool
    - hplt_repsetup_hpsetup_access_denied is defined
    - hplt_repsetup_hpsetup_set_register is defined
    - hplt_repsetup_hpsetup_access_denied in hplt_repsetup_hpsetup_set_register.stdout

- name: (hp linux tools) enable hplt_repsetup_hpsetup_set_bios when All BIOS options programmed successfully
  set_fact:
    hplt_repsetup_hpsetup_set_bios: true
  when:
    - hplt_repsetup_hpsetup_set_register is defined
    - hplt_repsetup_hpsetup_set_register.failed is defined
    - not hplt_repsetup_hpsetup_set_register.failed | bool
    - hplt_repsetup_hpsetup_set_register.rc == 0
    - hplt_repsetup_hpsetup_set_success in hplt_repsetup_hpsetup_set_register.stdout

- name: (hp linux tools) fail when not all BIOS options programmed successfully
  fail:
  when:
    - hplt_repsetup_hpsetup_set_all is defined
    - hplt_repsetup_hpsetup_set_all | bool
    - hplt_repsetup_hpsetup_set_bios is defined
    - not hplt_repsetup_hpsetup_set_bios | bool
