---

- name: (hp linux tools) BIOS download HPSETUP if missing or checksum differs
  get_url:
    url: "{{ hplt_repsetup_hpsetup_file_url }}"
    dest: "{{ hplt_repsetup_hpsetup_file_path }}"
    checksum: "{{ hplt_algorithm | lower }}:{{ hplt_repsetup_hpsetup_file_checksum }}"
    use_proxy: "{{ hplt_proxy_use }}"
    timeout: "{{ hplt_download_timeout | default(300) }}"
  environment: "{{ hplt_proxy_environment }}"
  become: yes
  when:
    - hplt_repsetup_hpsetup_down | bool
    - not hplt_repsetup_hpsetup_get | bool

- name: (hp linux tools) ensure hp-repsetup is executable
  file:
    path: "{{ hplt_repsetup_command_bin }}"
    owner: "{{ hplt_repsetup_owner }}"
    mode: "{{ hplt_repsetup_mode }}"
  become: yes

- name: (hp linux tools) BIOS get HPSETUP
  shell: "{{ hplt_repsetup_command_get }} > {{ hplt_repsetup_hpsetup_file_path }}"
  args:
    executable: /bin/bash
  become: yes
  when:
    - hplt_repsetup_hpsetup_get | bool
    - not hplt_repsetup_hpsetup_down | bool

- name: (hp linux tools) BIOS show HPSETUP
  command: strings {{ hplt_repsetup_hpsetup_file_path }}
  become: yes
  when: hplt_repsetup_hpsetup_show | bool

- name: (hp linux tools) BIOS test/set Admin Password
  command: "{{ hplt_repsetup_command_tst }}"
  ignore_errors: True
  no_log: "{{ hplt_repsetup_hpsetup_set_no_log | default(true) }}"
  register: hplt_repsetup_hpsetup_tst_register
  become: yes
  when:
    - hplt_repsetup_hpsetup_set is defined
    - hplt_repsetup_hpsetup_set | bool

- name: (hp linux tools) enable hplt_repsetup_hpsetup_pwd_admin when Admin Password test is successful
  set_fact:
    hplt_repsetup_hpsetup_pwd_admin: true
  when:
    - hplt_repsetup_hpsetup_tst_register is defined
    - hplt_repsetup_hpsetup_tst_register.failed is defined
    - not hplt_repsetup_hpsetup_tst_register.failed | bool
    - hplt_repsetup_hpsetup_tst_register.rc == 0
    - hplt_repsetup_hpsetup_pwd_success in hplt_repsetup_hpsetup_tst_register.stdout

