---

- name: (hp linux tools) get hp-repsetup command stat
  stat:
    path: "{{ hplt_repsetup_command_bin }}"
  register: hplt_repsetup_command_stat
  become: yes

- name: (hp linux tools) fails when hp-repsetup command does not exist
  fail:
    msg: not found {{ hplt_repsetup_command_bin }}
  when:
    - not hplt_repsetup_command_stat.stat.exists | bool

- name: (hp linux tools) fails when hplt_repsetup_password_current has invalid
  fail:
    msg: hplt_repsetup_password_current has invalid {{ hplt_repsetup_password_invalid }}
  no_log: "{{ hplt_repsetup_hpsetup_set_no_log | default(true) }}"
  when:
    - hplt_repsetup_password_invalid in hplt_repsetup_password_current | string

- name: (hp linux tools) fails when hplt_repsetup_password_new has invalid
  fail:
    msg: hplt_repsetup_password_new has invalid {{ hplt_repsetup_password_invalid }}
  no_log: "{{ hplt_repsetup_hpsetup_set_no_log | default(true) }}"
  when:
    - hplt_repsetup_password_invalid in hplt_repsetup_password_new | string

- name: (hp linux tools) BIOS update Admin Password
  command: "{{ hplt_repsetup_command_upd }}"
  ignore_errors: True
  no_log: "{{ hplt_repsetup_hpsetup_set_no_log | default(true) }}"
  register: hplt_repsetup_hpsetup_upd_register
  become: yes
  when:
    - hplt_repsetup_hpsetup_upd is defined
    - hplt_repsetup_hpsetup_upd | bool
    - hplt_repsetup_password_current is defined
    - hplt_repsetup_password_current | length > 0
    - hplt_repsetup_password_new is defined
    - hplt_repsetup_password_new | length > 0

- name: (hp linux tools) enable hplt_repsetup_update_admin when Admin Password update is successful
  set_fact:
    hplt_repsetup_update_admin: true
  when:
    - hplt_repsetup_hpsetup_upd_register is defined
    - hplt_repsetup_hpsetup_upd_register.failed is defined
    - not hplt_repsetup_hpsetup_upd_register.failed | bool
    - hplt_repsetup_hpsetup_upd_register.rc is defined
    - hplt_repsetup_hpsetup_upd_register.rc == 0
    - hplt_repsetup_hpsetup_pwd_success is defined
    - hplt_repsetup_hpsetup_pwd_success in hplt_repsetup_hpsetup_upd_register.stdout

- name: (hp linux tools) disable hplt_repsetup_update_admin when Admin Password already update
  set_fact:
    hplt_repsetup_update_admin: false
  when:
    - hplt_repsetup_hpsetup_upd_register is defined
    - hplt_repsetup_hpsetup_upd_register.failed is defined
    - hplt_repsetup_hpsetup_upd_register.failed | bool
    - hplt_repsetup_hpsetup_upd_register.rc == 136
    - hplt_repsetup_hpsetup_upd_failed in hplt_repsetup_hpsetup_upd_register.stdout

- name: (hp linux tools) fail when Admin Password update is failed
  fail:
  when:
    - hplt_repsetup_update_fail is defined
    - hplt_repsetup_update_fail | bool
    - hplt_repsetup_update_admin is defined
    - not hplt_repsetup_update_admin | bool
